### ISSUE TITLE
tap ./gradlew setupWorkspace 작업중 오류

### ISSUE THREAD

**Issue by ysw827** [monun/tap#1]
저는 tap을 다운받고 개발환경을 구축하기 위해 ./gradlew setupWorkspace로 작업하던 도중에 에러가 떴습니다 왜 이런걸까요?
> Configure project :
e: C:\Users\1023a\Downloads\tap-master\build.gradle.kts:180:55: Unresolved reference: nullOutputStream
e: C:\Users\1023a\Downloads\tap-master\build.gradle.kts:181:52: Unresolved reference: nullOutputStream

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\1023a\Downloads\tap-master\build.gradle.kts' line: 180

* What went wrong:
Script compilation errors:

  Line 180:                         standardOutput = OutputStream.nullOutputStream()
                                                                  ^ Unresolved reference: nullOutputStream

  Line 181:                         errorOutput = OutputStream.nullOutputStream()
                                                               ^ Unresolved reference: nullOutputStream

2 errors

**Comment by monun** [comment]
JDK11
