### ISSUE TITLE
빌드 오류

### ISSUE THREAD

**Issue by moozno** [monun/tap#17]
> Task :tap-api:signDokkaJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tap-api:signDokkaJar'.
> Cannot perform signing task ':tap-api:signDokkaJar' because it has no configured signatory

이렇게 뜨는데 어떻게 해야 하나요?

**Comment by qogusdn1017** [comment]
build.gradle.kta에서 signing 관련 내용들 제거
