### ISSUE TITLE
documentation 관련 문의

### ISSUE THREAD

**Issue by dytroInc** [monun/tap#2]
이 라이브러리에 documentation 같은 건 없나요?
만약에 있다면 어디에 있는지 애기해주는 걸 부탁드리고 없다면 docs 제작 의향이 있는지 애기 부탁드립니다.

**Comment by qogusdn1017** [comment]
현재로써는 Documentation이 없다고 하십니다. 바쁘시다고...

제작의향은 모르겠네요 누군가가 플리퀘 걸면 받아주실거같네요

**Comment by dytroInc** [comment]
> 현재로써는 Documentation이 없다고 하십니다. 바쁘시다고...
> 
> 제작의향은 모르겠네요 누군가가 플리퀘 걸면 받아주실거같네요

그렇군요. 감사합니다.

**Comment by monun** [comment]
저도 문서 만들고픕니다 ㅜ

**Comment by qogusdn1017** [comment]
https://monun.me/tap-getting-started

WIP

**Comment by dytroInc** [comment]
> https://monun.me/tap-getting-started
> 
> WIP

만들고 계시는 분이 있군요

**Comment by qogusdn1017** [comment]
> > https://monun.me/tap-getting-started
> > WIP
> 
> 만들고 계시는 분이 있군요

tap 부분은 저도 배워야하는 부분인지라 작업속도가 좀 늦을수도 있습니다 ㅠㅜ 다른분들께서 문서작업 하시긴 할텐데 그분들도 학업때매...

**Comment by issac4892** [comment]
혹시 찾으시면 https://monun.me/tap/getting-started
