### ISSUE TITLE
LibraryLoader

### ISSUE THREAD

**Issue by yuange86** [monun/tap#25]
LibraryLoader cannot load NMS or implement class which's constructor has more than zero parameters

LibraryLoader.kt (line:37,80) could be like:

constructor.newInstance(*initArgs) as T

**Comment by qogusdn1017** [comment]
정확히 어디 오류이신지...?

**Comment by yuange86** [comment]
LibraryLoader의 loadImplement를 호출할 때 initArgs에 인자를 전달하면 해당되는 생성자는 찾았다고 뜨는데 매개변수 전달에 문제가 뜬다고 나왔습니다. 그래서 코드를 찾아보니까 newInstance()에서 initArgs가 전달 안되있더라고요

**Comment by qogusdn1017** [comment]
ㅇㅎ
