### ISSUE TITLE
라이선스(?) 관련 문제

### ISSUE THREAD

**Issue by yuange86** [monun/tap#27]
저작권 문제로 묻게 되었습니다
제가 마인크래프트 라이브러리를 만드려 계획중인데 LibraryLoader.kt만 소스를 사용하려 합니다만 그런 경우에 해당 라이브러리 프로젝트를 GPL-3.0가 필수인가요?

제가 GPL 라이선스를 잘 몰라서 확인하고자 합니다.

**Comment by MisileLab** [comment]
tap을 라이브러리만 사용할려면 GPL이 적용안되고, 만약 직접 코드를 사용한다면 전부 공개하거나 두개를 독립된 라이브러리로 만드셔야 합니다. (이 경우 tap 사용한 라이브러리만 GPL 적용)

**Comment by yuange86** [comment]
> 만약 직접 코드를 사용한다면 전부 공개하거나 두개를 독립된 라이브러리로 만드셔야 합니다. (이 경우 tap 사용한 라이브러리만 GPL 적용)

답변 감사합니다.
그럼 프로젝트 안에 소스파일을 넣는 경우(수정을 한)에는 소스 공개 및 라이선스를 GPL-3.0로 변경해야 한다는 거네요

**Comment by MisileLab** [comment]
더 정확한 이해를 위해 예를 들어볼게요.
안드로이드 커널은 리눅스를 이용해서 GPL 라이선스에 따라 공개되어 있습니다.
그러나 나머지 안드로이드 코드는 아파치 라이선스로 되어있습니다.
이럴 경우, 안드로이드 커널은 직접적인 코드로 작동하는것이 아닌 CLI 방법 등으로(저도 잘 모릅니다)작동합니다.

**Comment by yuange86** [comment]
감사합니다. 덕분에 해결되었습니다.

**Comment by qogusdn1017** [comment]
해결 되셨다면 이슈 닫아주세요
