### ISSUE TITLE
라이선스 관련

### ISSUE THREAD

**Issue by nunonu** [monun/tap#3]
조금 주제에 벗어난 이슈이긴 합니다,

하지만 중요하기 때문에 올려봅니다.

정확히 Gradle에 컴파일 할 떄 GPL-3.0에 기준이 어떻게 되나요?

소스을 공개적으로 배포해야 하나요?

**Comment by monun** [comment]
판매 혹은 배포시에만 공개하시면 됩니다.

꽤 조항이 많으니 직접 검색해보세요

**Comment by nunonu** [comment]
아유 늦은 시간에도 답변하여 주셔서 대단히 감사합니다.
