### ISSUE TITLE
tap-api가 1.19.1에서 작동하지 않습니다.

### ISSUE THREAD

**Issue by MisileLab** [monun/tap#31]
tap api가 디펜던시를 다운로드 받을 수 없다면서 플러그인 로딩에 실패하는데 tap-api.pom에 있는 paper 버전이 1.18인것이 원인으로 보입니다.

**Comment by dolphin2410** [comment]
> tap api가 디펜던시를 다운로드 받을 수 없다면서 플러그인 로딩에 실패하는데 tap-api.pom에 있는 paper 버전이 1.18인것이 원인으로 보입니다.

혹시 로그를 보여주실 수 있나요?

**Comment by MisileLab** [comment]
https://pastebin.ubuntu.com/p/RSBmKcNXX4/

**Comment by MisileLab** [comment]
4.6.2는 잘 작동합니다. (아무래도 이 [커밋](https://github.com/monun/tap/commit/759498f9790d009a8f57d54f8d2aafd5be502e05)이 문제랑 관련있는 것 같습니다.)

**Comment by monun** [comment]
확인해보겠습니다

**Comment by dolphin2410** [comment]
[여기](https://github.com/monun/tap/blob/d02f4ca1602e8de3e6a291016fcfff28a3648a25/build.gradle.kts#L29)가 문제였던 것 같습니다
