### ISSUE TITLE
Passenger 상태의 머리 방향 조정

### ISSUE THREAD

**Issue by highright1234** [monun/tap#34]
최근에 Passenger 상태의 FakeEntity를 처리하는 도중에 생긴 문제였습니다   
Passenger 상태에서 바라보는 direction을 바꾸려 하였지만   
> setLocation  
> removePassenger후 setLocation, addPassenger 
> moveTo

세가지 모두 작동되지 않아 여러가지 방법을 찾아보며   
결국 PacketSupport의 entityTeleport로 변경하였습니다    
다른 방법으로 변경은 결국 안되는것같아 포기하였지만 바꾸는 다른 방법이 있는가유?   
아니면 일종의 버그인가유?

**Comment by monun** [comment]
코드 올려주시겠어요?

**Comment by monun** [comment]
https://github.com/monun/tap/commit/85efd5ebac23d9300eb44861081b2130465f7c3a
