### ISSUE TITLE
Config api 질문

### ISSUE THREAD

**Issue by highright1234** [monun/tap#39]
`ConfigSupport.compute(target: Any, config: ConfigurationSection, separateByClass: Boolean = false)`  
이 함수에서 separateByClass 변수가 있는데 기능상  
yaml에서 기본 class와 super-class들을 값마다 config-section이 나눠지게 돼 있는데  
```
        val configurables = target.javaClass.getConfigurables() 

        for ((clazz, list) in configurables) {
            val sectionPath = if (separateByClass) clazz.configKey else "" // <-
            var section = if (sectionPath.isNotBlank()) config.getConfigurationSection(sectionPath) else config

```

혹시 이부분은 실수인것인가유? 실수가 아니라면 어떤 의도로 인해 열어둔것인가유?

**Comment by monun** [comment]
넘 옛날 코드라 분석이 필요합니다요..

**Comment by monun** [comment]
아 separatebtclass 활성화시 나눠지는게 맞습니다
