### ISSUE TITLE
Metadata 지원에 대한 의문

### ISSUE THREAD

**Issue by dytroc** [monun/tap#42]
metadata를 사용할 때, 엔티티나 블록에게 메터데이터를 추가하고서 해당 메타데이터를 지워도 맵은 남아 있어 메모리 누수 문제가 있는 걸로 압니다.

거기다가 해당 메타데이터를 사용하는 엔티티가 사망할 경우, 맵이 남아있는 문제 때문에 웬만해서는 쓰지 않는 걸로 알고 있습니다.

이러한 메모리 누수 문제들 때문에 Paper 공식 디스코드 서버 측에서도 메타데이터 대신에 PDC를 쓰도록 장려하는데, 굳이 지원할 필요가 있는지 의문이 듭니다.

**Comment by monun** [comment]
내부 코드가 수상쩍긴하네요

**Comment by dytroc** [comment]
https://github.com/monun/tap/commit/6c215c3cbfd8065ffd834781d352c6e633b70a03

확인했습니다. 이슈 닫겠습니다.
