### ISSUE TITLE
Display 계열 FakeEntity가 표시되지 않음

### ISSUE THREAD

**Issue by ghost** [monun/tap#48]
ㅈㄱㄴ

현재 TextDisplay 동작 안되는거 확인되었음
다른 디스플레이 계열 확인예정, `world#spawn()`을 이용해서는 가능

Display 쪽은 잘 알려진게 없어서 제가 틀릴수도있어요

**Comment by dolphin2410** [comment]
paper 소스 확인해보니 Display가 EntityType.UNKNOWN을 반환하더군요

**Comment by dolphin2410** [comment]
`falling block`과 달리 addEntityPacket에서 entityData가 없는 거

**Comment by dolphin2410** [comment]
아마 Display도 FallingBlock처럼 따로 지원해야 할 듯 합니다??
